obstacle_range: 5.0
raytrace_range: 15.0 

footprint: [[-0.17, -0.20], [-0.20, -0.10], [-0.225, 0.0], [-0.20, 0.10], [-0.17, 0.20], [0.10, 0.20], [0.17, 0.10], [0.225, 0.0], [0.17, -0.10], [0.10, -0.20]]

footprint_padding: 0.01

inflation_radius: 0.20
max_obstacle_height: 0.6 
min_obstacle_height: 0.0 

observation_sources: laser_scan_sensor
laser_scan_sensor: {sensor_frame: laser, topic: /scan, data_type: LaserScan, clearing: true, marking: true}
